import sys

# 파일 읽기
with open('trade_guard_app.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# 1013번 라인까지만 유지 (0-based index이므로 0-1012)
fixed_lines = lines[:1013]

# 누락된 함수들 추가
new_code = '''
        output.seek(0)
        return output.getvalue()
    except Exception as e:
        st.error(f"엑셀 생성 오류: {e}")
        return None

def create_word_document(results, summary_data):
    """워드 문서 생성 (특이건만 상세 포함)"""
    try:
        doc = Document()
        doc.add_heading('수입신고 RISK 분석 보고서', 0)
        doc.add_paragraph(datetime.datetime.now().strftime("%Y-%m-%d"))
        
        if summary_data:
            doc.add_heading('종합 요약', level=1)
            p = doc.add_paragraph()
            p.add_run(f"전체 신고 건수: {summary_data.get('전체 신고 건수', 0):,} 건").bold = True
            
            if 'Risk분석' in summary_data:
                risk_df = summary_data['Risk분석']
                risk_found = risk_df[risk_df['신고건수'] > 0]
                
                if len(risk_found) > 0:
                    p.add_run(f"\\n\\n⚠️ 발견된 Risk 유형: {len(risk_found)}건").bold = True
                    for _, row in risk_found.iterrows():
                        p.add_run(f"\\n- {row['Risk 유형']}: {row['신고건수']:,} 건 ({row['비율(%)']:.1f}%)")
                else:
                    p.add_run("\\n\\n✅ 특이사항이 발견되지 않았습니다.").bold = True
        
        has_findings = False
        section_titles = {
            'eight_percent': ('8% 환급 검토', ['수입신고번호', '세번부호', '관세실행세율']),
            'zero_risk': ('0% 세율 위험', ['수입신고번호', '세번부호', '세율구분']),
        }
        
        for key, (title, cols) in section_titles.items():
            data = results.get(key)
            if data is not None and not data.empty:
                has_findings = True
                doc.add_heading(title, level=1)
                doc.add_paragraph(f'총 {len(data):,} 건이 식별되었습니다.')
        
        if not has_findings:
            doc.add_heading('분석 결과', level=1)
            doc.add_paragraph('✅ 특이사항이 발견되지 않았습니다.')
        
        doc.add_paragraph()
        footer = doc.add_paragraph('Generated by 관세법인 우신')
        footer.alignment = 1
        
        doc_output = io.BytesIO()
        doc.save(doc_output)
        doc_output.seek(0)
        return doc_output.getvalue()
    except Exception as e:
        st.error(f"워드 문서 생성 중 오류 발생: {str(e)}")
        return None

def create_html_report(results, summary_data):
    """HTML 보고서 생성"""
    try:
        html = f"""<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>수입신고 RISK 분석</title>
</head>
<body>
    <h1>수입신고 RISK 분석 보고서</h1>
    <p>Generated by 관세법인 우신</p>
</body>
</html>"""
        return html
    except Exception as e:
        st.error(f"HTML 보고서 생성 중 오류: {str(e)}")
        return None

def main():
    st.title("🛡️ TradeGuard")
    st.sidebar.caption("made by 전자동")
    
    uploaded_file = st.file_uploader("파일 업로드", type=['xlsx', 'xls', 'csv'])
    if uploaded_file:
        df_original = read_excel_file(uploaded_file)
        if df_original is not None:
            st.success("데이터 로드 완료!")
            
            if st.sidebar.button("분석 시작"):
                results = {}
                results['summary'] = create_summary_analysis(df_original)
                
                excel_data =  create_excel_file(df_original, results, results.get('summary', {}))
                if excel_data:
                    st.download_button("엑셀 다운로드", excel_data, "report.xlsx")

if __name__ == "__main__":
    main()
'''

# 수정된 내용 쓰기
with open('trade_guard_app_fixed.py', 'w', encoding='utf-8') as f:
    f.writelines(fixed_lines)
    f.write(new_code)

print("파일 수정 완료! trade_guard_app_fixed.py 생성됨")
